import type { Metadata } from "next"

export const metadata: Metadata = {
    title: 'About',
    description: 'Generated by create next app',
  }

export default function AboutPage(){
    return(
        <main className="flex flex-col items-center">
            <h1 className="text-slate-700 text-7xl">About</h1>
        </main>
    )
}