import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AboutPage from './components/about/page'
import Navbar from './components/navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Aplicación Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <Navbar/>
      <div className='h-max p-24'>
        <AboutPage/>
        { children }
      </div>
    </html>
  )
}
