import type { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Pricing',
    description: 'Generated by create next app',
  }

export default function PricingPage(){
    return(
        <>
        <div></div>
            <h1 className="">Pricing</h1>
        </>
    )
}