import type { Metadata } from "next"

export const metadata: Metadata = {
    title: 'Contact',
    description: 'Generated by create next app',
  }

export default function ContactPage(){
    return(
        <>
            <span></span>
        </>
    )
}